#!/usr/bin/env python3
"""Generate IPC name registries and verify the manual Tauri authority gates."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_RELATIVE = Path("config/ipc-commands.json")
RUST_OUTPUT_RELATIVE = Path("apps/lorepia/src-tauri/generated/app_commands.rs")
TYPESCRIPT_OUTPUT_RELATIVE = Path(
    "apps/lorepia/src/lib/ipc/commands.generated.ts"
)
PERMISSIONS_RELATIVE = Path("apps/lorepia/src-tauri/permissions/autogenerated")
BASE_TAURI_CONFIG_RELATIVE = Path("apps/lorepia/src-tauri/tauri.conf.json")
BASE_TAURI_CAPABILITY = "main-development"
CAPABILITY_SELECTIONS = (
    (
        "development",
        Path("apps/lorepia/src-tauri/tauri.dev.conf.json"),
        "main-development",
        Path("apps/lorepia/src-tauri/capabilities/main-development.json"),
    ),
    (
        "release",
        Path("apps/lorepia/src-tauri/tauri.release.conf.json"),
        "main-release",
        Path("apps/lorepia/src-tauri/capabilities/main-release.json"),
    ),
)
COMMAND_RE = re.compile(r"[a-z][a-z0-9]*(?:_[a-z0-9]+)*")
TYPESCRIPT_KEY_RE = re.compile(r"[a-z][A-Za-z0-9]*")


def typescript_key(command: str) -> str:
    """Derive the public lower-camel-case TypeScript key for a command."""

    head, *tail = command.split("_")
    return head + "".join(part[0].upper() + part[1:] for part in tail)


def load_commands(manifest_path: Path) -> tuple[str, ...]:
    """Load and validate the command-name-only manifest."""

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read IPC command manifest {manifest_path}: {error}") from error
    if not isinstance(manifest, dict) or manifest.get("version") != 1:
        raise ValueError("IPC command manifest version must be 1")
    if set(manifest) != {"version", "commands"}:
        raise ValueError("IPC command manifest must contain only version and commands")
    values = manifest.get("commands")
    if not isinstance(values, list) or not values:
        raise ValueError("IPC command manifest commands must be a non-empty array")

    commands: list[str] = []
    command_names: set[str] = set()
    typescript_keys: set[str] = set()
    for index, value in enumerate(values):
        if not isinstance(value, str) or COMMAND_RE.fullmatch(value) is None:
            raise ValueError(
                f"IPC command at index {index} must be a lowercase snake_case name"
            )
        key = typescript_key(value)
        if TYPESCRIPT_KEY_RE.fullmatch(key) is None:
            raise ValueError(f"IPC command {value} does not produce a valid TypeScript key")
        if value in command_names:
            raise ValueError(f"duplicate IPC command name: {value}")
        if key in typescript_keys:
            raise ValueError(f"duplicate IPC TypeScript key: {key}")
        commands.append(value)
        command_names.add(value)
        typescript_keys.add(key)
    return tuple(commands)


def render_rust(commands: Sequence[str]) -> str:
    lines = [
        "// @generated by scripts/generate_ipc_commands.py from config/ipc-commands.json.",
        "// Do not edit this file directly.",
        "",
        "const APP_COMMANDS: &[&str] = &[",
    ]
    lines.extend(f'    "{command}",' for command in commands)
    lines.append("];")
    return "\n".join(lines) + "\n"


def render_typescript(commands: Sequence[str]) -> str:
    lines = [
        "// @generated by scripts/generate_ipc_commands.py from config/ipc-commands.json.",
        "// Do not edit this file directly.",
        "",
        "export const LOREPIA_COMMANDS = {",
    ]
    for command in commands:
        key = typescript_key(command)
        line = f"    {key}: '{command}',"
        if len(line) <= 100:
            lines.append(line)
        else:
            lines.extend([f"    {key}:", f"        '{command}',"])
    lines.append("} as const;")
    return "\n".join(lines) + "\n"


def render_permission(command: str) -> str:
    """Reproduce Tauri's reviewed single-command permission artifact."""

    identifier = command.replace("_", "-")
    return (
        "# Automatically generated - DO NOT EDIT!\n\n"
        "[[permission]]\n"
        f'identifier = "allow-{identifier}"\n'
        f'description = "Enables the {command} command without any pre-configured scope."\n'
        f'commands.allow = ["{command}"]\n\n'
        "[[permission]]\n"
        f'identifier = "deny-{identifier}"\n'
        f'description = "Denies the {command} command without any pre-configured scope."\n'
        f'commands.deny = ["{command}"]\n'
    )


def load_json_object(path: Path, label: str) -> dict[str, object]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read {label} {path}: {error}") from error
    if not isinstance(value, dict):
        raise ValueError(f"{label} {path} must be a JSON object")
    return value


def selected_capabilities(config: dict[str, object], path: Path) -> object:
    try:
        app = config["app"]
        if not isinstance(app, dict):
            raise KeyError("app")
        security = app["security"]
        if not isinstance(security, dict):
            raise KeyError("security")
        return security["capabilities"]
    except KeyError as error:
        raise ValueError(
            f"Tauri config {path} must declare app.security.capabilities"
        ) from error


def capability_selection_failures(
    root: Path, commands: Sequence[str]
) -> list[str]:
    """Keep each mode bound to the reviewed ID and exact manual command grants."""

    failures: list[str] = []
    expected_grants = {
        f"allow-{command.replace('_', '-')}" for command in commands
    }
    base_path = root / BASE_TAURI_CONFIG_RELATIVE
    base = load_json_object(base_path, "base Tauri config")
    if selected_capabilities(base, BASE_TAURI_CONFIG_RELATIVE) != [
        BASE_TAURI_CAPABILITY
    ]:
        failures.append(
            f"{BASE_TAURI_CONFIG_RELATIVE} must select only capability "
            f"{BASE_TAURI_CAPABILITY}; an empty list enables every capability file"
        )

    for mode, config_relative, expected_identifier, capability_relative in CAPABILITY_SELECTIONS:
        config = load_json_object(root / config_relative, f"{mode} Tauri config")
        actual_selection = selected_capabilities(config, config_relative)
        if actual_selection != [expected_identifier]:
            failures.append(
                f"{config_relative} must select only capability {expected_identifier}"
            )

        capability = load_json_object(
            root / capability_relative, f"{mode} Tauri capability"
        )
        if capability.get("identifier") != expected_identifier:
            failures.append(
                f"{capability_relative} identifier must be {expected_identifier}"
            )
        if capability.get("local") is not True:
            failures.append(f"{capability_relative} must remain local-only")
        if capability.get("windows") != ["main"]:
            failures.append(f"{capability_relative} must target only the main window")
        if "remote" in capability:
            failures.append(f"{capability_relative} must not grant remote origins")
        permissions = capability.get("permissions")
        if not isinstance(permissions, list) or not all(
            isinstance(permission, str) for permission in permissions
        ):
            failures.append(
                f"{capability_relative} permissions must be a string array"
            )
            continue
        app_grants = [
            permission
            for permission in permissions
            if permission.startswith("allow-")
        ]
        if len(app_grants) != len(set(app_grants)):
            failures.append(
                f"{capability_relative} cannot contain duplicate app-command grants"
            )
        if set(app_grants) != expected_grants:
            failures.append(
                f"{capability_relative} must grant exactly the manifest app commands"
            )
    return failures


def tracked_permission_paths(root: Path) -> set[Path]:
    process = subprocess.run(
        [
            "git",
            "ls-files",
            "-z",
            "--cached",
            "--",
            PERMISSIONS_RELATIVE.as_posix(),
        ],
        cwd=root,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if process.returncode != 0:
        detail = process.stderr.decode(errors="replace").strip()
        raise ValueError(f"cannot inspect tracked IPC permissions with git: {detail}")
    return {
        Path(os.fsdecode(value))
        for value in process.stdout.split(b"\0")
        if value
    }


def permission_artifact_failures(root: Path, commands: Sequence[str]) -> list[str]:
    """Reject missing, stale, extra, modified, or untracked Tauri permissions."""

    directory = root / PERMISSIONS_RELATIVE
    expected = {
        PERMISSIONS_RELATIVE / f"{command}.toml": command for command in commands
    }
    actual = (
        {
            path.relative_to(root): path
            for path in directory.iterdir()
            if path.is_file() and path.suffix == ".toml"
        }
        if directory.is_dir()
        else {}
    )
    tracked = tracked_permission_paths(root)
    failures: list[str] = []

    for relative in sorted(expected.keys() - actual.keys()):
        failures.append(f"missing generated IPC permission {relative}")
    for relative in sorted(actual.keys() - expected.keys()):
        failures.append(f"unexpected generated IPC permission {relative}")
    for relative in sorted(expected.keys() - tracked):
        failures.append(f"generated IPC permission is not tracked by git: {relative}")
    for relative in sorted(tracked - expected.keys()):
        if relative.parent == PERMISSIONS_RELATIVE and relative.suffix == ".toml":
            failures.append(f"stale tracked IPC permission {relative}")

    for relative in sorted(expected.keys() & actual.keys()):
        try:
            contents = actual[relative].read_text(encoding="utf-8")
        except OSError as error:
            failures.append(f"cannot read generated IPC permission {relative}: {error}")
            continue
        if contents != render_permission(expected[relative]):
            failures.append(f"generated IPC permission has non-canonical content: {relative}")
    return failures


def expected_outputs(root: Path) -> dict[Path, str]:
    commands = load_commands(root / MANIFEST_RELATIVE)
    return {
        root / RUST_OUTPUT_RELATIVE: render_rust(commands),
        root / TYPESCRIPT_OUTPUT_RELATIVE: render_typescript(commands),
    }


def stale_outputs(outputs: dict[Path, str]) -> list[Path]:
    stale: list[Path] = []
    for path, expected in outputs.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            stale.append(path)
            continue
        if actual != expected:
            stale.append(path)
    return stale


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, contents in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as temporary:
            temporary.write(contents)
            temporary_path = Path(temporary.name)
        os.replace(temporary_path, path)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=REPO_ROOT,
        help="repository root containing config/ipc-commands.json",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "fail without writing when registries, tracked permissions, or "
            "capability selections drift"
        ),
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    root = args.root.resolve()
    try:
        commands = load_commands(root / MANIFEST_RELATIVE)
        outputs = {
            root / RUST_OUTPUT_RELATIVE: render_rust(commands),
            root / TYPESCRIPT_OUTPUT_RELATIVE: render_typescript(commands),
        }
    except ValueError as error:
        print(f"IPC command codegen: {error}")
        return 1

    if args.check:
        failures: list[str] = []
        stale = stale_outputs(outputs)
        if stale:
            for path in stale:
                try:
                    relative = path.relative_to(root)
                except ValueError:
                    relative = path
                failures.append(
                    f"IPC command codegen: stale or missing {relative}; "
                    "run scripts/generate_ipc_commands.py"
                )
        try:
            failures.extend(
                f"IPC command codegen: {failure}"
                for failure in permission_artifact_failures(root, commands)
            )
        except ValueError as error:
            failures.append(f"IPC command codegen: {error}")
        try:
            failures.extend(
                f"IPC command codegen: {failure}"
                for failure in capability_selection_failures(root, commands)
            )
        except ValueError as error:
            failures.append(f"IPC command codegen: {error}")
        if failures:
            for failure in failures:
                print(failure)
            return 1
        print("IPC command codegen: PASS")
        return 0

    write_outputs(outputs)
    print("IPC command codegen: generated Rust and TypeScript registries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
